version: "3"

services:
  client:
    image: remoting-client:latest
    restart: always
    ports:
      - 9091:9090
  server:
    image: remoting-server:latest
    hostname: remoting-server
    ports:
      - 9090:9090
    restart: always